// ui/src/Routes/Login.svelte
<script>
	import { Link, navigate } from 'svelte-routing'
	import { loggedIn } from '../stores'
	import { postJSON } from '../fetchJSON'

	let email, password, error = ''
	let sending = false

	const handleSubmit = async () => {
		const data = {email, password}
		try {
			await postJSON('/api/login', data)
			$loggedIn = true
			navigate('/')
		} catch (err) {
			error = '' + err
		}
	}
</script>

<h1 class="f3 f2-m f1-l fw2 mv3">
	Login
</h1>
<p>If you haven't already, <Link to="register" class="no-underline green">create an account</Link> to start monitoring.</p>

<form on:submit|preventDefault={handleSubmit}>
	<fieldset id="sign_up" class="ba b--transparent ph0 mh0">
		<legend class="ph0 mh0 fw6 clip">Sign Up</legend>
		<div class="mt3">
			<label class="db fw4 lh-copy f6" for="email-address">Email address</label>
			<input 
				class="pa2 input-reset ba bg-transparent w-100 measure" 
				type="email" 
				name="email"
				bind:value={email}
			/>
		</div>
		<div class="mt3">
			<label class="db fw4 lh-copy f6" for="password">Password</label>
			<input 
				class="b pa2 input-reset ba bg-transparent w-100 measure"
				type="password"
				name="password"  
				bind:value={password}
			/>
		</div>
	</fieldset>

	{#if error.length > 0}
		<div class="mt3">
			<p class="red">{error}</p>
		</div>
	{/if}

	<div class="mt3">
		{#if sending}
			<p>Logging in...</p>
		{:else}
			<button type="submit" class="f4 bb bt-0 bl-0 br-0 bw2 b--dark-green br2 pointer dim ph3 pv2 mt5 fw3 mb2 dib white bg-green grow">Let me in!</button>
		{/if}
	</div>
</form>

// ui/src/routes/login.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import { Page } from '../components/wrapper'
import { useLogin } from '../context/login'
import { useHistory } from 'react-router-dom'

const Login = () => {
	const { postLogin } = useLogin()
	const history = useHistory()

	const [email, setEmail] = React.useState('')
	const [password, setPassword] = React.useState('')
	const [idle, setIdle] = React.useState(true)
	const [error, setError] = React.useState('')

	const handleSubmit = async (e) => {
		setIdle(false)

		e.preventDefault()

		setError('')

		try {
			await postLogin(email, password)
			history.push('/')
		} catch (error) {
			setError('' + error)
			setTimeout(() => {
				setIdle(true)
			}, 1000)
		}
	}

	return (
		<Page>
			<h1 className="f3 f2-m f1-l fw2 mv3">
				Login
			</h1>
			<p>If you haven't already, <Link to="register" className="no-underline green">create an account</Link> to start monitoring.</p>

			<form onSubmit={handleSubmit}>
				<fieldset id="sign_up" className="ba b--transparent ph0 mh0">
					<legend className="ph0 mh0 fw6 clip">Sign Up</legend>
					<div className="mt3">
						<label className="db fw4 lh-copy f6" htmlFor="email-address">Email address</label>
						<input 
							className="pa2 input-reset ba bg-transparent w-100 measure" 
							type="email" 
							name="email"
							value={email}
							onChange={e => setEmail(e.target.value)}
						/>
					</div>
					<div className="mt3">
						<label className="db fw4 lh-copy f6" htmlFor="password">Password</label>
						<input 
							className="b pa2 input-reset ba bg-transparent w-100 measure"
							type="password"
							name="password"  
							value={password}
							onChange={e => setPassword(e.target.value)}
						/>
					</div>
				</fieldset>

				{
					error.length > 0 && 
						<div className="mt3">
							<p className="red">{error}</p>
						</div>
				}

				<div className="mt3">
					{ idle && <input className="pointer input-reset f4 dim br1 ph3 pv2 bn mb2 dib white bg-green grow" type="submit" value="Let me in!" /> }
					{ !idle && <p>Logging in...</p> }
				</div>
			</form>
		</Page>
	)
}

export default Login
